#!/usr/bin/sh
export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/git/bin:$HOME/.bin:$PATH"

export EDITOR=vim
export GIT_EDITOR=vim

export GEM_HOME="$HOME/gems"
export PATH="$GEM_HOME/bin:$PATH"
export PRODUCTION_MODE=False

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias ll='ls -alFsh'
alias lfl='ls -lF'
alias la='ls -A'
alias l='ls -CF'
#alias python='python3'
#alias pip='pip3'
alias venv='python3 -m venv'
alias monosed='sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"'
alias dollarsed='sed "s/¤/$/g"'
alias jcurl='curl -s -H "Content-Type: application/json"'
alias jget='curl -s -X GET -H "Content-Type: application/json"'
alias jpost='curl -s -X POST -H "Content-Type: application/json"'
alias jqcount="jq '. | to_entries | map(.value.count=.key+1) | [.[].value]'"
#jg() { jget "$@" | jq '.'; } 
#jp() { jpost "$@" | jq '.'; }

# LOLOL
alias dood,=sudo

# local profile settings
if [ -f ~/.profile_local ]; then
	source ~/.profile_local
fi
