#!/usr/bin/sh
export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/git/bin:$HOME/.bin:$HOME/.local/bin:$PATH"

export EDITOR=vim
export GIT_EDITOR=vim

export GEM_HOME="$HOME/gems"
export PATH="$GEM_HOME/bin:$PATH"

export CARGO_HOME="$HOME/.cargo"
export PATH="$CARGO_HOME/bin:$PATH"

export GOROOT="/usr/local/go"
export GOPATH="$HOME/go"
export PATH="$GOROOT/bin:$PATH"

export PRODUCTION_MODE=False
export TZ="UTC"

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias ll='ls -alF --time-style="+%d-%b-%Y %H:%M:%S %Z"'
alias la='ls -A'
alias l='ls -CF'
alias venv='python3 -m venv'
alias monosed='sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"'
alias dollarsed='sed "s/¤/$/g"'
alias colorit="highlight $@ --out-format xterm256 --force"
alias tabawk='awk "{print \"\t\"\$0}"'
alias 2sawk='awk "{print \"  \"\$0}"'
alias 4sawk='awk "{print \"    \"\$0}"'
alias tmuxbase='tmux attach -t base || tmux new -s base'
alias rcp='rsync -ah --partial --progress'
alias rscp='rsync -ah --partial --progress --rsh=ssh'
alias jcurl='curl -s -H "Content-Type: application/json"'
alias jget='curl -s -X GET -H "Content-Type: application/json"'
alias jpost='curl -s -X POST -H "Content-Type: application/json"'
alias jqcount="jq '. | to_entries | map(.value.count=.key+1) | [.[].value]'"
function dirSize { du -sc --exclude="lost+found" * | sort -n | awk '{size=$1; $1=""; gsub(/^ */,"",$0); printf "%10.3f MB    %-s\n",size/1024,$0}'; }
function dirSizeG { du -sc --exclude="lost+found" * | sort -n | awk '{size=$1; $1=""; gsub(/^ */,"",$0); printf "%10.3f GB    %-s\n",size/1024/1024,$0}'; }

# LOLOL
alias dood,=sudo

# local profile settings
if [ -f ~/.profile_local ]; then
    source ~/.profile_local
fi
