#!/usr/bin/env python
"""json2yaml: Compact script for json to yaml conversion"""

import yaml
import json
import sys


args = [open(x,'r') for x in sys.argv[1:]]
args = [sys.stdin.read(), *args] if not sys.stdin.isatty() else args
loadjson = lambda x: json.loads(x) if isinstance(x,str) else json.load(x)
files = [loadjson(y) for y in args]
out = files[0] if len(files) == 1 else files

sys.stdout.write(yaml.dump(out))

