#!/usr/bin/bash
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# code from dotfiles/sh/myprofile
. ~/.myprofile

DAOS_DEFAULT_COLOR="[00m"
DAOS_GRAY_COLOR="[37m"
DAOS_PINK_COLOR="[01;35m"
DAOS_GREEN_COLOR="[01;32m"
DAOS_ORANGE_COLOR="[01;33m"

daos_vcinfo() {
  echo -e "$(vcprompt -f " on \033[34m%n\033[00m:%b\033[32m%m%u")"
}

export DAOS_BASEPROMPT="\n\e${DAOS_PINK_COLOR}\u \
\e${DAOS_GRAY_COLOR}at \e${DAOS_ORANGE_COLOR}\h \
\e${DAOS_GRAY_COLOR}in \e${DAOS_GREEN_COLOR}\w\
\e${DAOS_GRAY_COLOR}\$(daos_vcinfo)\
\e${DAOS_DEFAULT_COLOR}"
export PS1="${DAOS_BASEPROMPT}
$ "

# always support 256 colors
export TERM=xterm-256color

# append to the history file, don't overwrite it
shopt -s histappend

export HISTTIMEFORMAT="%a, %d %b %Y %H:%M:%S "

# check and update the window size after each command
shopt -s checkwinsize

# enable programmable completion features 
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi	

# local bashrc
if [ -f ~/.bashrc.local ]; then
  . ~/.bashrc.local
fi
