#!/usr/bin/bash
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# code from dotfiles/sh/myprofile
. ~/.myprofile

DAOS_DEFAULT_COLOR="[00m"
DAOS_GRAY_COLOR="[37m"
DAOS_PINK_COLOR="[01;35m"
DAOS_GREEN_COLOR="[01;32m"
DAOS_ORANGE_COLOR="[01;33m"
DAOS_RED_COLOR="[01;31m"
DAOS_CYAN_COLOR="[01;36m"

daos_lastcommandfailed() {
  code=$?
  if [ $code != 0 ]; then
    echo -n $'\033[37m exited \033[31m'
    echo -n $code
    echo -n $'\033[37m'
  fi
}

daos_backgroundjobs() {
  jobs|python -c 'if 1:
    import sys
    items = ["\033[36m%s\033[37m" % x.split()[2]
             for x in sys.stdin.read().splitlines()]
    if items:
      if len(items) > 2:
        string = "%s, and %s" % (", ".join(items[:-1]), items[-1])
      else:
        string = ", ".join(items)
      print("\033[37m running %s" % string)
  '
}

daos_venvinfo() {
  if [[ -n "$VIRTUAL_ENV" ]]; then
    venv="${VIRTUAL_ENV##*/}"
  else
    venv=''
  fi
  [[ -n "$venv" ]] && echo -e " \033[37mworkon \033[31m$venv"
}

daos_vcinfo() {
  echo -e "$(vcprompt -f " \033[37mon \033[34m%n\033[00m:%b\033[32m%m%u")"
}

daos_time() {
  echo -n $'\033[37m during \033[36m'
  echo -n $(date -u +"%a, %d %b %Y %H:%M:%S %Z" | sed 's/UTC/GMT/g')
  echo -n $'\033[37m'
}

export VIRTUAL_ENV_DISABLE_PROMPT=1

export DAOS_BASEPROMPT="\n\e${DAOS_PINK_COLOR}\u \
\e${DAOS_GRAY_COLOR}at \e${DAOS_ORANGE_COLOR}\h \
\e${DAOS_GRAY_COLOR}in \e${DAOS_GREEN_COLOR}\w\
\$(daos_lastcommandfailed)\
\$(daos_backgroundjobs)\
\$(daos_venvinfo)\
\$(daos_time)\
\$(daos_vcinfo)\
\e${DAOS_DEFAULT_COLOR}"
export PS1="${DAOS_BASEPROMPT}
\#: "

# always support 256 colors
export TERM=xterm-256color

# append to the history file, don't overwrite it
shopt -s histappend

export HISTTIMEFORMAT="%a, %d %b %Y %H:%M:%S "

# check and update the window size after each command
shopt -s checkwinsize

# enable programmable completion features 
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi	

# local bashrc
if [ -f ~/.bashrc.local ]; then
  . ~/.bashrc.local
fi
